CREATE TABLE [dbo].[Item] (
    [Prod_ID]         VARCHAR (20)  NOT NULL,
    [Ref_Doc_ID]      VARCHAR (20)  NOT NULL,
    [Inventory_ID]    VARCHAR (20)  NULL,
    [Reason]          VARCHAR (100) NULL,
    [Remark]          VARCHAR (100) NULL,
    [PackingSlipNo]   VARCHAR (20)  NULL,
    [Qty]             INT           NOT NULL,
    [Ori_Qty]         INT           NOT NULL,
    [Unit_Price]      MONEY         NULL,
    [Delivery_Date]   DATE          NULL,
    [Excl_Amount]     MONEY         NULL,
    [Discount_Amount] MONEY         NULL,
    [Incl_Amount]     MONEY         NULL,
    CONSTRAINT [PK_Item] PRIMARY KEY CLUSTERED ([Prod_ID] ASC, [Ref_Doc_ID] ASC),
    CONSTRAINT [FK_Item_CustomerInquiry] FOREIGN KEY ([Ref_Doc_ID]) REFERENCES [dbo].[CustomerInquiry] ([CI_ID]),
    CONSTRAINT [FK_Item_DeliveryOrder] FOREIGN KEY ([Ref_Doc_ID]) REFERENCES [dbo].[DeliveryOrder] ([DO_ID]),
    CONSTRAINT [FK_Item_Inventory] FOREIGN KEY ([Inventory_ID]) REFERENCES [dbo].[Inventory] ([Inventory_ID]),
    CONSTRAINT [FK_Item_PackingSlip] FOREIGN KEY ([Ref_Doc_ID]) REFERENCES [dbo].[PackingSlip] ([PS_ID]),
    CONSTRAINT [FK_Item_Product1] FOREIGN KEY ([Prod_ID]) REFERENCES [dbo].[Product] ([Prod_ID]),
    CONSTRAINT [FK_Item_Quotation] FOREIGN KEY ([Ref_Doc_ID]) REFERENCES [dbo].[Quotation] ([QUOT_ID]),
    CONSTRAINT [FK_Item_Receipt] FOREIGN KEY ([Ref_Doc_ID]) REFERENCES [dbo].[Receipt] ([RCPT_ID]),
    CONSTRAINT [FK_Item_ReturnDeliveryNote] FOREIGN KEY ([Ref_Doc_ID]) REFERENCES [dbo].[ReturnDeliveryNote] ([RDN_ID]),
    CONSTRAINT [FK_Item_SalesOrder] FOREIGN KEY ([Ref_Doc_ID]) REFERENCES [dbo].[SalesOrder] ([SO_ID]),
    CONSTRAINT [FK_Item_TransferOrder] FOREIGN KEY ([Ref_Doc_ID]) REFERENCES [dbo].[TransferOrder] ([TO_ID])
);
